name: utils
description: Flutter/Dart utils.
version: 3.0.0
author: OeCore
homepage: https://www.oecore.com

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  ansicolor: ^2.0.0
  device_info_plus: ^9.0.0
  daylight: ^2.0.0
  fast_gbk: ^1.0.0

  event_bus: ^2.0.0
  dio: ^4.0.0
  sqflite: ^2.0.0
  moor_flutter: ^4.0.0
  fixnum: ^1.0.0
  decimal: ^2.1.0
  hex: ^0.2.0
  quiver: ^3.0.0
  socket_io_client: ^2.0.0-beta.3-nullsafety.0
  shared_preferences: ^2.0.0
  uuid: ^3.0.1
  # quick_usb: ^0.4.0
  usb_device: ^1.0.2

  package_info_plus: ^4.0.0
  lpinyin: ^2.0.1

  #网络状态
  connectivity_plus: ^4.0.0
  android_multicast_lock: ^1.0.2
  # battery_plus: ^2.1.3
  battery_info: ^1.1.1
  screen_brightness: ^0.2.0
  volume_controller: ^2.0.3
  # coordinate transform
  coordtransform_dart: ^1.0.0
  lehttp_overrides: ^1.0.2

  buffer:
    git: https://github.com/w-rui/buffer.git
  native_http:
    git: https://github.com/w-rui/native_http.git
  flutter_blue:
    git: https://github.com/w-rui/flutter_blue.git
  crclib:
    git: https://github.com/w-rui/crclib.dart.git
  bt_broadcast: ^0.0.1
  better_log: ^0.0.1
#  utils:
#    path: ../utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_web_compilers:
  build_runner:
  source_gen:
  sqflite_common_ffi:
  mockito:
  build:
  meta:
  analyzer: ^4.0.0
  #  analyzer: 0.39.14
  #  functional_data_generator: ^0.3.4
  #  analyzer: ^0.39.14
  translator: ^0.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
